name: Docs
on: [push]
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.8
      - name: Install requirements
        run: |
          pip install -r requirements.txt
          pip install -e .
      - name: Build docs
        run: make html
        working-directory: ./docs_src
      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4.11.0
        with:
          commit_message: Build docs
          repository: docs
